---
swagger: "2.0"
info:
  description: "OpenReq Requirement Prioritization Recommendation Service"
  version: "1.0.0"
  title: "OpenReq Requirement Prioritization Recommendation Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "rsamer@ist.tugraz.at"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "217.172.12.199:9002"
basePath: "/"
tags:
- name: "recommend"
  description: "OpenReq Requirement Dependency Recommendation Service"
schemes:
- "http"
paths:
  /prioritizer/compute:
    post:
      tags:
      - "Recommender"
      summary: "Retrieve a list of prioritized issues."
      description: ""
      operationId: "recommend_prioritized_issues"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Request object"
        required: true
        schema:
          $ref: "#/definitions/Requirement"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PrioritizedRecommendationsResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "application.controllers.recommendation_controller"
  /prioritizer/chart:
    post:
      tags:
      - "Recommender"
      summary: "Retrieve the chart URL."
      description: ""
      operationId: "generate_chart_url"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "Request object"
        required: true
        schema:
          $ref: "#/definitions/Requirement"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PrioritizedRecommendationsResponse"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "application.controllers.recommendation_controller"
definitions:
  Requirement:
    type: "object"
    properties:
      assignee:
        type: "string"
      components:
        type: "array"
        items:
          type: "string"
      products:
        type: "array"
        items:
          type: "string"
      keywords:
        type: "array"
        items:
          type: "string"
  PrioritizedRecommendationsResponse:
    type: "object"
    properties:
      error:
        type: "boolean"
      errorMessage:
        type: "string"
#      rankedBugs:
#        type: "array"
#        items:
#          type: "object"
#          properties:
#            id:
#              type: "integer"
#              format: "int64"
#            summary:
#              type: "string"
#            product:
#              type: "string"
#            component:
#              type: "string"
#            priority:
#              type: "number"
#              format: "float"
#              minimum: "0"
#              maximum: "1"
#            numberOfCC:
#              type: "integer"
#              format: "int32"
#            milestone:
#              type: "string"
    xml:
      name: "recommendations"
